# Generated by Django 4.1.7 on 2023-03-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0002_remove_ticket_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="hotel",
        ),
        migrations.AddField(
            model_name="trip",
            name="hotel",
            field=models.ManyToManyField(related_name="trips", to="manager.hotel"),
        ),
    ]
