# Generated by Django 4.1.7 on 2023-03-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0003_remove_trip_hotel_trip_hotel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="id",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="number",
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
    ]
